language: ruby
rvm:
  - 2.1
branches:
  only:
  - source
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
gemfile:
  - Gemfile
exclude: [vendor]
script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site/