title: Cyberflow
description: My Personal Blog
author: Cyberflow
github: https://github.com/cyberflow
about: I am linux system administrator.
email: dmitry.r@cyberflow.net
urls:
    - text: Categories
      url: /category/
    - text: Github
      url: https://github.com/cyberflow
    - text: XML Feed
      url: /feed.xml
url: "https://cyberflow.net"
baseurl: ""
paginate: 5
per_page: 5
paginate_path: "/page:num/"
markdown: kramdown
kramdown:
  input: GFM

disqus_short_name: cyberflowblog

gems:
  - jekyll-gravatar

exclude:
  - Gemfile
  - Gemfile.lock

excerpt_separator: <!--more-->
excerpt_link: "Read on &rarr;"