title: Cyberflow
description: My Personal Blog
author: Cyberflow
github: https://github.com/cyberflow
about: I am linux system administrator.
username: cyberflow
email: dmitry.r@cyberflow.net
urls:
    - text: Categories
      url: /category/
    - text: Code
      url: /code/
    - text: XML Feed
      url: /feed.xml
url: "https://cyberflow.net"
baseurl: ""
paginate: 5
per_page: 5
paginate_path: "/page:num/"
permalink: /:year/:month/:title.html
markdown: kramdown
kramdown:
  input: GFM

disqus_short_name: cyberflowblog

plugins:
  - jekyll-gravatar
  - jekyll-categories
  - jekyll-multiple-languages-plugin

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .travis
  - travis_rsa.enc
  - source_readme.md

excerpt_separator: <!--more-->
excerpt_link: "Read on &rarr;"

category_dir: 'category'

# Google Analytics
google_analytics_tracking_id: 'UA-31213444-1'

# multiple language plugin config
languages: ['ru', 'en']
exclude_from_localizations: ['static', '_posts']

# atom jekyll plugin config
atom:
  buildCommand:
    - bundle
    - exec
    - jekyll
    - build
