title: Cyberflow
description: My Personal Blog
author: Cyberflow
github: https://github.com/cyberflow
about: I am system administrator.
email: dmitry.r@cyberflow.net
urls:
    - text: Category
      url: /category/
    - text: Github
      url: https://github.com/cyberflow
    - text: XML Feed
      url: /feed.xml
url: "https://cyberflow.net"
baseurl: ""
paginate: 5
per_page: 5
paginate_path: "/page:num/"
markdown: kramdown

gems:
  - jekyll-gravatar

exclude:
  - Gemfile
  - Gemfile.lock